sepetteYemek/sepetteYemek/Models/siniflar/personel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Xml.Linq;

namespace sepetteYemek.Models.siniflar
{
    public class personel
    {

        [Key]
        public int Personelid { get; set; }

        [Display(Name = "Personel Adı")]

        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string PersonelAd { get; set; }
        [Display(Name = "Personel Soyadı")]

        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string PersonelSoyad { get; set; }
        [Display(Name = "Personel Görsel")]

        [Column(TypeName = "Varchar")]
        [StringLength(250)]
        public string PersonelGorsel { get; set; }
        public ICollection<satisHareket> SatisHarekets { get; set; }
        //bir personel sadece bir depatmanda bulunabilir
        public int departmanid { get; set; }
        public virtual departman Departman { get; set; }
    }
}

sepetteYemek/sepetteYemek/Controllers/personelController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using sepetteYemek.Models.siniflar;
namespace sepetteYemek.Controllers
{
    public class personelController : Controller
    {
        // GET: personel
        context sb=new context();
        public ActionResult Index(string p)
        {
            var degerler = from x in sb.Personels select x;
            if (!string.IsNullOrEmpty(p))
            {
                degerler = degerler.Where(y => y.PersonelAd.Contains(p));

            }
            return View(degerler.ToList());
        }
        [HttpGet]
        //[Authorize(Roles = "A")]

        public ActionResult personelEkle()
        {
            List<SelectListItem> deger1 = (from x in sb.Departmans.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.DepartmanAd,
                                               Value = x.Departmanid.ToString()

                                           }).ToList();
            ViewBag.x = deger1;

            return View();
        }
        [HttpPost]
        public ActionResult personelEkle(personel p)
        {
            if (Request.Files.Count > 0)
            {
                string dosyaadi = Path.GetFileName(Request.Files[0].FileName);
                string uzanti = Path.GetExtension(Request.Files[0].FileName);
                string yol = "~/Image/" + dosyaadi + uzanti;
                Request.Files[0].SaveAs(Server.MapPath(yol));
                p.PersonelGorsel = "/Image/" + dosyaadi + uzanti;
            }
            sb.Personels.Add(p);
            sb.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult personelGetir(int id)
        {
            List<SelectListItem> deger2 = (from x in sb.Departmans.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.DepartmanAd,
                                               Value = x.Departmanid.ToString()

                                           }).ToList();
            ViewBag.dgr1 = deger2;

            var prs = sb.Personels.Find(id);
            return View("PersonelGetir", prs);

        }
        public ActionResult PersonelGuncelle(personel p)
        {
            //if (Request.Files.Count > 0)
            //{
            //    string dosyaadi = Path.GetFileName(Request.Files[0].FileName);
            //    string uzanti = Path.GetExtension(Request.Files[0].FileName);
            //    string yol = "~/Image/" + dosyaadi + uzanti;
            //    Request.Files[0].SaveAs(Server.MapPath(yol));
            //    p.PersonelGorsel = "/Image/" + dosyaadi + uzanti;
            //}
            var prs = sb.Personels.Find(p.Personelid);
            prs.PersonelAd = p.PersonelAd;
            prs.PersonelSoyad = p.PersonelSoyad;
            prs.PersonelGorsel = p.PersonelGorsel;
            prs.departmanid = p.departmanid;
            sb.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

sepetteYemek/sepetteYemek/Views/personel/Index.cshtml
@using sepetteYemek.Models.siniflar
@model List<personel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}


@using (Html.BeginForm("Index", "Personel", FormMethod.Get))
{
    <p>
        Ürün Adı : @Html.TextBox("p")
        <input type="submit" value="ara" />
    </p>

}
<table class="table table-bordered" style="margin-top:20px">
    <tr>
        <th>Personel Ad</th>
        <th>Soyad</th>
        <th>Görsel</th>
        <th>Departman</th>
        <th>Güncelle</th>
        <th>Satışlar</th>
    </tr>
    @foreach (var k in Model)
    {
        <tr>
            <td>@k.PersonelAd</td>
            <td>@k.PersonelSoyad</td>
            <td>
                <img src="@k.PersonelGorsel" style="width:100px;height:70px" />
            </td>
            <td>@k.Departman.DepartmanAd</td>

            <td><a href="/personel/personelGetir/@k.Personelid" class="btn btn-warning">Güncelle</a></td>
            <td><a href="/departman/departmanPersonelSatis/@k.Personelid" class="btn btn-success" style="background-color:blueviolet">Detaylar</a></td>
        </tr>
    }

</table>

<a href="/personel/personelEkle" class="btn btn-info">Personel Ekle</a>

sepetteYemek/sepetteYemek/Views/personel/personelEkle.cshtml
@model sepetteYemek.Models.siniflar.personel
@{
    ViewBag.Title = "personelEkle";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<br />
<h2>Yeni Personel Sayfası</h2>

<br />
@using (Html.BeginForm("personelEkle", "personel", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <form class="form-group" method="post">
        @Html.LabelFor(s => s.PersonelAd)
        @Html.TextBoxFor(s => s.PersonelAd, new { @class = "form-control" })
        <br />
        @Html.LabelFor(s => s.PersonelSoyad)
        @Html.TextBoxFor(s => s.PersonelSoyad, new { @class = "form-control" })
        <br />
        @Html.LabelFor(s => s.PersonelGorsel)
        @*@Html.TextBoxFor(s => s.PersonelGorsel, new { @class = "form-control" })*@
        <input type="file" name="PersonelGorsel" />
        <br />
        @Html.LabelFor(s => s.Departman)
        @*@Html.TextBoxFor(s => s.Kategoriid, new { @class = "form-control" })*@
        @Html.DropDownListFor(s => s.departmanid, (List<SelectListItem>)ViewBag.x, new { @class = "form-control" })
        <br />
        <button class="btn btn-primary">Kaydet</button>

    </form>

}

sepetteYemek/sepetteYemek/Views/personel/personelGetir.cshtml
@model sepetteYemek.Models.siniflar.personel
@{
    ViewBag.Title = "personelGetir";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<h2>PersonelGetir</h2>

@using (Html.BeginForm("PersonelGuncelle", "Personel", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-group">
        @Html.HiddenFor(s => s.Personelid)
        @Html.LabelFor(s => s.PersonelAd)
        @Html.TextBoxFor(s => s.PersonelAd, new { @class = "form-control" })
        <br />
        @Html.LabelFor(s => s.PersonelSoyad)
        @Html.TextBoxFor(s => s.PersonelSoyad, new { @class = "form-control" })
        <br />
        @Html.LabelFor(s => s.PersonelGorsel)
        <input type="file" name="PersonelGorsel" />
        <br />
        @Html.LabelFor(s => s.Departman)
        @Html.DropDownListFor(s => s.departmanid, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
        <br />
    </div>
    <button class="btn btn-info"> Güncelle</button>
}