sepetteYemek/sepetteYemek/Models/siniflar/musteri.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace sepetteYemek.Models.siniflar
{
    public class musteri
    {
        [Key]
        public int musteriid { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string musteriAd { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string musteriSoyad { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(15)]
        public string musteriSehir { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(50)]
        public string musteriMail { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(20)]
        public string musteriSifre { get; set; }
        public bool Durum { get; set; }
        public ICollection<satisHareket> SatisHarekets { get; set; }
    }
}

sepetteYemek/sepetteYemek/Controllers/musteriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using sepetteYemek.Models.siniflar;
namespace sepetteYemek.Controllers
{
    public class musteriController : Controller
    {
        // GET: musteri
        context sb = new context();
        public ActionResult Index()
        {
            var degerler = sb.Carilers.Where(s => s.Durum == true).ToList();
            return View(degerler);
        }
        [HttpGet]
        //[Authorize(Roles = "A")]

        public ActionResult YeniMusteri()
        {

            return View();
        }
        [HttpPost]

        public ActionResult YeniMusteri(musteri cr)
        {
            cr.Durum = true;
            sb.Carilers.Add(cr);
            sb.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult musteriSil(int id)
        {
            var cr = sb.Carilers.Find(id);
            cr.Durum = false;
            sb.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult musteriGetir(int id)
        {
            var cari = sb.Carilers.Find(id);
            return View("musteriGetir", cari);
        }
        public ActionResult musteriGuncelle(musteri ca)
        {

            var cari = sb.Carilers.Find(ca.musteriid);
            cari.musteriAd = ca.musteriAd;
            cari.musteriSoyad = ca.musteriSoyad;
            cari.musteriSehir = ca.musteriSehir;
            cari.musteriMail = ca.musteriMail;

            sb.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult musteriSatis(int id)
        {
            var satislar = sb.SatisHarekets.Where(s => s.musteriid == id).ToList();
            var cr = sb.Carilers.Where(s => s.musteriid == id).Select(b => b.musteriAd + " " + b.musteriSoyad).FirstOrDefault();
            ViewBag.cari = cr;

            return View(satislar);
        }
    }
}

sepetteYemek/sepetteYemek/Views/musteri/Index.cshtml
@using sepetteYemek.Models.siniflar
@model List<musteri>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<br />

<table class="table table-striped">
    <tr>
        <th>Müşteri</th>
        <th>Ad</th>
        <th>Soyad</th>
        <th>Şehir</th>
        <th>Mail</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Detaylar</th>
    </tr>
    @foreach (var k in Model)
    {

        <tr>

            <td>
                @k.musteriid

            </td>
            <td>
                @k.musteriAd
            </td>
            <td>
                @k.musteriSoyad
            </td>
            <td>
                @k.musteriSehir
            </td>
            <td>
                @k.musteriMail
            </td>
            <td><a href="/musteri/musteriSil/@k.musteriid" class="btn btn-danger">Sil</a></td>
            <td><a href="/musteri/musteriGetir/@k.musteriid" class="btn btn-warning">Güncelle</a></td>
            <td><a href="/musteri/musteriSatis/@k.musteriid" class="btn btn-success" style="background-color:blueviolet">Alım Geçmişi</a></td>
        </tr>
    }

</table>

<a href="/musteri/YeniMusteri" class="btn btn-info">Müşteri Ekle</a>

sepetteYemek/sepetteYemek/Views/musteri/YeniMusteri.cshtml
@model sepetteYemek.Models.siniflar.musteri
@{
    ViewBag.Title = "YeniMusteri";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<br />
<h2>Yeni Müşteri Sayfası</h2>
<script src="~/Scripts/jquery-3.4.1.js"></script>

<br />
<form class="form-group" method="post">
    @Html.LabelFor(s => s.musteriAd)
    @Html.TextBoxFor(s => s.musteriAd, new { @class = "form-control" })
    <br />
    @Html.LabelFor(s => s.musteriSoyad)
    @Html.TextBoxFor(s => s.musteriSoyad, new { @class = "form-control" })
    <br />
    @Html.LabelFor(s => s.musteriSehir)
    @Html.TextBoxFor(s => s.musteriSehir, new { @class = "form-control" })
    <br />
    @Html.LabelFor(s => s.musteriMail)
    @Html.TextBoxFor(s => s.musteriMail, new { @class = "form-control" })
    <br />
    <button class="btn btn-info" id="Btn1">Kaydet</button>

    <script>
        $('#Btn1').click(function () {
            alert("Müşteri başarılı bir şekilde eklendi")
        }
        );
    </script>

</form>

sepetteYemek/sepetteYemek/Views/musteri/musteriGetir.cshtml
@model sepetteYemek.Models.siniflar.musteri
@{
    ViewBag.Title = "musteriGetir";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}


<br />
<h2>Müşteri Güncelleme Sayfası</h2>
<br />

@using (Html.BeginForm("musteriGuncelle", "musteri", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(s => s.musteriAd)
        @Html.TextBoxFor(s => s.musteriAd, new { @class = "form-control" })
        @Html.ValidationMessageFor(s => s.musteriAd, "", new { @style = "color:red" })
        <br />
        @Html.LabelFor(s => s.musteriSoyad)
        @Html.TextBoxFor(s => s.musteriSoyad, new { @class = "form-control" })
        @Html.ValidationMessageFor(s => s.musteriSoyad, "", new { @style = "color:red" })
        <br />
        @Html.LabelFor(s => s.musteriSehir)
        @Html.TextBoxFor(s => s.musteriSehir, new { @class = "form-control" })
        <br />
        @Html.LabelFor(s => s.musteriMail)
        @Html.TextBoxFor(s => s.musteriMail, new { @class = "form-control" })
        <br />
        @Html.HiddenFor(s => s.musteriid)
    </div>
    <button class="btn btn-info"> Güncelle</button>
}

sepetteYemek/sepetteYemek/Views/musteri/musteriSatis.cshtml
@using sepetteYemek.Models.siniflar
@model List<satisHareket>
@{
    ViewBag.Title = "musteriSatis";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Müşteri Adı> @ViewBag.cari</li>
</ol>
<table class=" table table-condensed">
    <tr>
        <th>Satış Id</th>
        <th>Ürün</th>
        <th>Personel</th>
        <th>Fiyat</th>
        <th>Adet</th>
        <th>Toplam</th>
        <th>Tarih</th>
        <th>Yazdır</th>

    </tr>

    @foreach (var s in Model)
    {
        <tr>
            <td>@s.Satisid</td>
            <td>@s.Urun.UrunAd</td>
            <td>@s.Personel.PersonelAd @s.Personel.PersonelSoyad</td>
            <td>@s.Fiyat</td>
            <td>@s.Adet</td>
            <td>@s.ToplamTutar</td>
            <td>@s.Tarih</td>
            <td><a href="#" class="btn btn-default" style="background-color:dodgerblue">Yazdır</a></td>
        </tr>
    }
</table>